### ISSUE TITLE
pgBackRest Docs Typo

### ISSUE THREAD

**Issue by carneytyler** [percona/k8spg-docs#210]
Hi, I found a couple small issues in the docs, `pgbouncer != pgbackrest`

- https://docs.percona.com/percona-operator-for-postgresql/2.0/operator.html#backupspgbackrestcontainerspgbouncerconfigresourceslimitscpu
- https://docs.percona.com/percona-operator-for-postgresql/2.0/operator.html#backupspgbackrestcontainerspgbouncerconfigresourceslimitscpu

![image](https://github.com/user-attachments/assets/744ea1e2-2575-4844-9629-5a579aa84d29)

**Comment by fiowro** [comment]
Fixed!
